repo_url: https://github.com/hect0x7/JMComic-Crawler-Python
repo_name: hect0x7/JMComic-Crawler-Python
site_name: jmcomic

theme:
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 切换到浅色主题
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到深色主题
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 主题跟随系统
  name: material
  features:
    - navigation.sections
    - content.code.copy
    - content.code.select
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.top
nav:
  - 首页: index.md
  - 版本更新计划: roadmap.md
  - 配置文件指南: option_file_syntax.md
  - Api 文档:
    - api/client.md
    - api/command-line.md
    - api/config.md
    - api/download.md
    - api/entity.md
    - api/option.md
    - api/plugin.md
    - api/toolkit.md
  - 使用教程:
    - tutorial/0_common_usage.md
    - tutorial/1_github_actions.md
    - tutorial/2_command_line.md
    - tutorial/4_module_custom.md
    - tutorial/5_filter.md
    - tutorial/6_plugin.md
    - tutorial/7_advance.md
    - tutorial/8_pick_domain.md
    - tutorial/9_custom_download_dir_name.md
    - tutorial/10_export_favorites.md
    - tutorial/11_log_custom.md
    - tutorial/12_domain_strategy.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          paths: [ '../../src/' ]
          options:
            summary:
              functions: true
            preload_modules:
              - common
            docstring_style: sphinx


markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

docs_dir: sources